apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: hypercloud-secret-watcher
  namespace: hypercloud-system
  labels:
    hypercloud: secret-watcher
spec:
  selector:
    matchLabels:
      hypercloud: secret-watcher
  template:
    metadata:
      labels:
        hypercloud: secret-watcher
    spec:
      containers:
      - name: registry-watcher
        image: 192.168.6.110:5000/hyper-cloud-secret-watcher:b4.1.0.1
        imagePullPolicy: Always
        resources:
          limits:
            cpu: "100m"
            memory: "512Mi"
          requests:
            cpu: "100m"
            memory: "512Mi"
        volumeMounts:
        - name: cert-dir
          mountPath: /etc/docker/certs.d
        - name: docker-dir
          mountPath: /root/.docker
      terminationGracePeriodSeconds: 30
      serviceAccountName: hypercloud-admin
      volumes:
      - name: cert-dir
        hostPath:
          path: /etc/docker/certs.d
      - name: docker-dir
        hostPath:
          path: /root/.docker
