apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: images.tmax.co.kr
spec:
  group: tmax.co.kr
  versions:
    - name: v1
      served: true
      storage: true
  scope: Cluster
  names:
    plural: images
    singular: image
    kind: Image
    shortNames:
    - img
  preserveUnknownFields: false
  validation:
    openAPIV3Schema:
      type: object
      required: [spec, status]
      properties:
        spec:
          type: object
          required: [registryURL, name, tag]
          description: UserInfo contains user information
          properties:
            registryURL:
              type: string
            name:
              type: string
            tag:
              type: string