apiVersion: v1
kind: Namespace
metadata:
  name: hypercloud4-system
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: hypercloud4-system-quota
  namespace: hypercloud4-system
spec:
  hard:
    limits.cpu: "4"
    limits.memory: "20Gi"
    requests.storage: "30Gi"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: hypercloud4-admin
  namespace: hypercloud4-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: hypercloud4-admin
  namespace: hypercloud4-system
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: hypercloud4-admin
subjects:
  - kind: ServiceAccount
    name: hypercloud4-admin
    namespace: hypercloud4-system
roleRef:
  kind: ClusterRole
  name: hypercloud4-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: registry-config
  namespace: hypercloud4-system
data:
  config.yml: |
    version: 0.1
    log:
      fields:
        service: registry
    storage:
      cache:
        blobdescriptor: inmemory
      filesystem:
        rootdirectory: /var/lib/registry
      delete:
        enabled: true
    http:
      addr: :5000
      headers:
        X-Content-Type-Options: [nosniff]
    health:
      storagedriver:
        enabled: true
        interval: 10s
        threshold: 3
    notifications:
      endpoints:
      - name: hypercloud4-operator
        url: http://hypercloud4-operator-service.hypercloud4-system:28677/registry/event
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: hypercloud4-secret-watcher
  namespace: hypercloud4-system
  labels:
    hypercloud4: secret-watcher
spec:
  selector:
    matchLabels:
      hypercloud4: secret-watcher
  template:
    metadata:
      labels:
        hypercloud4: secret-watcher
    spec:
      containers:
      - name: hypercloud4-secret-watcher
        image: tmaxcloudck/hypercloud4-secret-watcher:b4.1.0.10a
        imagePullPolicy: Always
        env:
        - name: TZ
          value: Asia/Seoul
        - name: LOGLEVEL
          value: INFO # TRACE, DEBUG, INFO, WARN, ERROR, ALL or OFF
        resources:
          limits:
            cpu: "50m"
            memory: "100Mi"
          requests:
            cpu: "50m"
            memory: "100Mi"
        volumeMounts:
        - name: cert-dir
          mountPath: /etc/docker/certs.d
        - name: docker-dir
          mountPath: /root/.docker
      terminationGracePeriodSeconds: 30
      serviceAccountName: hypercloud4-admin
      volumes:
      - name: cert-dir
        hostPath:
          path: /etc/docker/certs.d
      - name: docker-dir
        hostPath:
          path: /root/.docker
