apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: hypercloud4-secret-watcher
  namespace: hypercloud4-system
  labels:
    hypercloud4: secret-watcher
spec:
  selector:
    matchLabels:
      hypercloud4: secret-watcher
  template:
    metadata:
      labels:
        hypercloud4: secret-watcher
    spec:
      containers:
      - name: hypercloud4-secret-watcher
        image: tmaxcloudck/hypercloud4-secret-watcher:b4.1.0.10
        imagePullPolicy: Always
        env:
        - name: TZ
          value: Asia/Seoul
#        resources:
#          limits:
#            cpu: "50m"
#            memory: "100Mi"
#          requests:
#            cpu: "50m"
#            memory: "100Mi"
        volumeMounts:
        - name: cert-dir
          mountPath: /etc/docker/certs.d
        - name: docker-dir
          mountPath: /root/.docker
      terminationGracePeriodSeconds: 30
#      serviceAccountName: hypercloud4-admin
      volumes:
      - name: cert-dir
        hostPath:
          path: /etc/docker/certs.d
      - name: docker-dir
        hostPath:
          path: /root/.docker